from __future__ import division, print_function
import sys, os, glob, time, warnings, gc
import numpy as np
import matplotlib.pyplot as plt
from astropy.table import Table, vstack, hstack, join
import fitsio

from multiprocessing import Pool


def poly_val1d(x, m):
    '''
    Evaluate the 1D polynomial from x values and polynomial parameters

    See also rlm_fit1d.py

    INPUT:
    1D array of x values;
    1D array of polynomial parameters (for example generated by rlm_fit1d.py).

    OUTPUT:
    1D array of the evaluated values of the polynomial.
    '''

    order = len(m)-1
    z = np.zeros(x.shape)
    for i in range(order+1):
        z += m[i] * x**i
    return z


coeffs_bprp = {'g': np.array([0.0943831406, -0.4808108043, 0.7298039749, -0.5374281288,
        0.1798823422, -0.0221753451]),
 'r': np.array([-0.0245318152, -0.0738853237, 0.1345020306, -0.0950945343,
        0.0291715143, -0.0032814652]),
 'i': np.array([-0.0170704976, -0.0772361509, 0.1480465738, -0.1097889482,
        0.0351804096, -0.0040910050]),
 'z': np.array([0.0343113536, -0.2291033723, 0.3789074132, -0.2558053076,
        0.0771598826, -0.0085946623])}

coeffs_g = {'g': np.array([-21.5420872857, 7.8721086052, -1.1143173025, 0.0770267149,
        -0.0026122840, 0.0000348608]),
 'r': np.array([-5.5828289761, 2.3038666644, -0.3529032546, 0.0258166810,
        -0.0009136725, 0.0000125904]),
 'i': np.array([38.5968859355, -11.3170276254, 1.3176510313, -0.0760647158,
        0.0021756498, -0.0000246618]),
 'z': np.array([-74.1502977912, 21.0783020838, -2.3658428359, 0.1308302345,
        -0.0035542063, 0.0000377703])}

gaia_columns = ['PHOT_G_MEAN_MAG', 'PHOT_BP_MEAN_MAG', 'PHOT_RP_MEAN_MAG', 'flux_g', 'flux_r', 'flux_i', 'flux_z']
sweep_columns = ['RA', 'DEC', 'MASKBITS', 'FLUX_G', 'FLUX_R', 'FLUX_I', 'FLUX_Z', 'FLUX_IVAR_G', 'FLUX_IVAR_R', 'FLUX_IVAR_I', 'FLUX_IVAR_Z', 'FRACFLUX_G', 'FRACFLUX_R', 'FRACFLUX_I', 'FRACFLUX_Z', 'ANYMASK_G', 'ANYMASK_R', 'ANYMASK_I', 'ANYMASK_Z']

fns = sorted(glob.glob('/global/cfs/cdirs/desi/users/rongpu/data/gaia_dr3/dr11_south_cross_match/*-gaia.fits'))


def read_file(fn):

    print(fn)
    gaia = Table(fitsio.read(fn, columns=gaia_columns))
    cat = Table(fitsio.read(fn.replace('-gaia.fits', '-ls.fits'), columns=sweep_columns))

    mask = (gaia['PHOT_G_MEAN_MAG']>13.5) & (gaia['PHOT_G_MEAN_MAG']<17.65)
    gaia = gaia[mask]
    cat = cat[mask]

    maskbits = [0, 1, 10, 12, 13]
    mask_clean = np.ones(len(cat), dtype=bool)
    for bit in maskbits:
        mask_clean &= (cat['MASKBITS'] & 2**bit)==0
    gaia = gaia[mask_clean]
    cat = cat[mask_clean]

    return gaia, cat


n_process = 128
with Pool(processes=n_process) as pool:
    res = pool.map(read_file, fns, chunksize=1)

gaia = vstack([res[ii][0] for ii in range(len(res))])
cat = vstack([res[ii][1] for ii in range(len(res))])

with warnings.catch_warnings():
    warnings.simplefilter('ignore')
    cat['gmag'] = 22.5 - 2.5*np.log10(cat['FLUX_G'])
    cat['rmag'] = 22.5 - 2.5*np.log10(cat['FLUX_R'])
    cat['imag'] = 22.5 - 2.5*np.log10(cat['FLUX_I'])
    cat['zmag'] = 22.5 - 2.5*np.log10(cat['FLUX_Z'])
    gaia['gmag'] = 22.5 - 2.5*np.log10(gaia['flux_g'])
    gaia['rmag'] = 22.5 - 2.5*np.log10(gaia['flux_r'])
    gaia['imag'] = 22.5 - 2.5*np.log10(gaia['flux_i'])
    gaia['zmag'] = 22.5 - 2.5*np.log10(gaia['flux_z'])

for band in ['g', 'r', 'i', 'z']:
    bprp = (gaia['PHOT_BP_MEAN_MAG']-gaia['PHOT_RP_MEAN_MAG'])
    gaia_g = gaia['PHOT_G_MEAN_MAG'].copy()
    gaia[band+'mag_std'] = gaia[band+'mag'] + poly_val1d(bprp, coeffs_bprp[band])
    gaia[band+'mag_std'] += poly_val1d(gaia_g, coeffs_g[band])

new = Table()
new['RA'] = cat['RA']
new['DEC'] = cat['DEC']
mask0 = (gaia['PHOT_BP_MEAN_MAG']-gaia['PHOT_RP_MEAN_MAG'])>0.6
mask0 &= (gaia['PHOT_BP_MEAN_MAG']-gaia['PHOT_RP_MEAN_MAG'])<2.5

for band in ['g', 'r', 'i', 'z']:
    new[band+'mag_diff'] = cat[band+'mag'] - gaia[band+'mag_std']
    new[band+'mag_diff'] = cat[band+'mag'] - gaia[band+'mag_std']
    new[band+'_valid'] = (cat['ANYMASK_'+band.upper()]==0)
    new[band+'_valid'] &= (cat['FLUX_'+band.upper()]>0) & (cat['FLUX_IVAR_'+band.upper()]>0) & (cat['FRACFLUX_'+band.upper()]<0.1)
    new[band+'_valid'] &= mask0

new.write('/global/cfs/cdirs/desi/users/rongpu/data/gaia_dr3/misc/gaia_dr11_south_offsets.fits')
